# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9649a6745b9a9051185440a92efc58ef5ca0a72275b6bf69fd57a0e8a97b95cfcfe73e8dfd17e3c92453d858fd90efb20983a4651b1551e79e8dbbb4950bce6

test:
  secret_key_base: a7710203ccef62ccd77265f4a68b0ddd5e80089646082b833cd6d384dfdde6ba6cb0d485e57fad56d09fa57c6143cec5950eafb3043f7f3a6717c548f21f03da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
